### ISSUE TITLE
add docmentation how to init angular controller

### ISSUE THREAD

**Issue by BenjaminBeck** [Liplex/MultipleFileUploadBundle#8]
it took me some time to find out that i need

```
{% block html_attributes %}{% spaceless %}
 ng-app="app" {{ parent() }}
{% endspaceless %}{% endblock %}
```
in my ```standard_layout.html.twig``` (never used angular before ..)

**Comment by christian-kolb** [comment]
@BenjaminBeck I'm sorry, I didn't have any notifications set on the repository and just stumbled over the issue now. I added it to the README file. Thanks for the input.
